### PR TITLE
Wrap semop() call so it syscalls semop() instead of semtimedop().

### LINKED ISSUE #36: Focal armhf and arm64 builds fail with semop: function not implemented:
Opening a ticket with notes copied from: https://github.com/osrf/multiarch-docker-image-generation/pull/35 . See also @clalancette's comment https://github.com/osrf/multiarch-docker-image-generation/pull/35#issuecomment-601699447 . @j-rivero also says similar errors are happening on http://build.osrfoundation.org

 The Noetic Focal armhf and arm64 jobs jobs all started failling 2 days ago.

* [Example successful job on March 3](http://build.ros.org/view/Nbin_ufhf_uFhf/job/Nbin_ufhf_uFhf__rosbash__ubuntu_focal_armhf__binary/5/consoleText)
* [Same job failing on March 18](http://build.ros.org/view/Nbin_ufhf_uFhf/job/Nbin_ufhf_uFhf__rosbash__ubuntu_focal_armhf__binary/6/consoleText)

# Random Notes

* Only armhf and arm64 jobs on Ubuntu Focal are failing
  * Focal amd64, Buster amd64, and Buster arm64 jobs are not failing
* The last successful job was 6 days ago, and the first failure was 2 days ago, so it must be from a change after March 13th but before March 17th.
* For all failing jobs, it shows in the console as:
```
dpkg-source: info: using options from ros-noetic-pcl-msgs-0.3.0/debian/source/options: --auto-commit
 fakeroot debian/rules clean
semop(1): encountered an error: Function not implemented
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 1
E: Building failed
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 138, in build_binarydeb
    subprocess.check_call(cmd, cwd=source_dir)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-noetic-pcl-msgs']' returned non-zero exit status 1.
```
* The error happens when [fakeroot calls the syscall `semop()` to decrement a semaphore](https://salsa.debian.org/clint/fakeroot/-/blob/master/communicate.c#L409)
* The error `Function not implemented` is what `perror()` prints when a syscall returns [`ENOSYS`](http://man7.org/linux/man-pages/man3/errno.3.html)
* `ENOSYS` is [not one of the documented error codes for `semop()`](http://man7.org/linux/man-pages/man2/semop.2.html#ERRORS)
* qemu seems to translate syscalls, including `semop()`, [though I wasn't able to find a spot where it would return `ENOSYS` in the `stable-3.1` branch](https://github.com/qemu/qemu/blob/920019e0e0e19c11c5b88adbab8b1b269f907709/linux-user/syscall.c#L3437-L3445).
* Both old successful and new failing jobs use the [same build of `osrf/ubuntu_armhf:focal`](https://hub.docker.com/layers/osrf/ubuntu_armhf/focal/images/sha256-47ad139e811b8971448e6673eb33e6739a18888f6ab183f9e1131db4d8dc4f90?context=explore) and [`osrf_ubuntu_arm64:focal`](https://hub.docker.com/layers/osrf/ubuntu_arm64/focal/images/sha256-f91ff5876473eea58bd90ca9900b0fba4d23999825230144665059f910112bb7?context=explore), meaning they have exactly the same version of qemu, so that hasn't changed.
* Both old successful and new failing jobs use the same version of `fakeroot`, `1.24-1`
* Both old successful and new failing jobs use the exact same version of Docker, though I'm not sure how involved it would be in syscalls since the container uses the host's kernel.
```
+ docker version
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:28:19 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:26:54 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
* @clalancette says the path to investigate is `fakeroot`-> container `glibc` -> `qemu` -> host `glibc` -> `kernel`
* Successful job had container `glibc` version `2.30-0ubuntu3`
* Failing job had container `glibc` version `2.31-0ubuntu6`

### PR DESCRIPTION
**Pull request by sloretz**
Fixes #36

This works around glibc 2.31 wrapping `semop()` as a syscall to `semtimedop()`, which qemu does not support, by adding a library to `/etc/ld.so.preload` that wraps `semop()` as a syscall to `semop()`.

### CODE REVIEW

File: wrap_semop.c [hunk 1]
```diff
@@ -0,0 +1,14 @@
+#include <unistd.h>
+#include <asm/unistd.h>
+#include <sys/syscall.h>
+
+/* Forward declare to avoid compiler warning */
+struct sembuf;
```
Comment (clalancette) [inline wrap_semop.c]: It's just a pointer, so it doesn't matter *too* much, but we can get an equivalent thing by:

```
#include <linux/sem.h>
```

File: build-image.sh [hunk 2]
```diff
@@ -153,6 +153,12 @@ fi
 chroot $chroot_dir dpkg-divert --local --rename --add /sbin/initctl
 chroot $chroot_dir ln -sf /bin/true /sbin/initctl
 
+### Build semop wrapper
+cp wrap_semop.c $chroot_dir/tmp/
+chroot $chroot_dir apt-get -y install build-essential
+chroot $chroot_dir gcc -fPIC -shared -o /opt/libpreload-semop.so /tmp/wrap_semop.c
+chroot $chroot_dir printf /opt/libpreload-semop.so > $chroot_dir/etc/ld.so.preload
```
Comment (clalancette) [inline build-image.sh]: Nit: simple `echo` should work here.

**Review by clalancette — APPROVED** [review]
Two really minor things; feel free to ignore if you don't think they are worth it.  Can I also suggest that you open an issue with upstream [qemu](https://bugs.launchpad.net/qemu/) to follow-up for the "real" fix for this issue?

File: wrap_semop.c (hunk 1 above)
Comment (sloretz) [reply wrap_semop.c]: Include header in 1b4a7c64509494168eddb88321ca62bc6f6cd2a8

File: build-image.sh (hunk 2 above)
Comment (sloretz) [reply build-image.sh]: Echo in e41f5379a7a7af2117678ad3695ee1ceebd39d01

**Comment by sloretz** [comment]
> Can I also suggest that you open an issue with upstream qemu to follow-up for the "real" fix for this issue?

Will do!
